require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "Say hello"
task :say_hi do 
    puts "Hello Mod One!"
end

desc "set up database"
task :create_book_db do 
    book_sql = <<-SQL 
        CREATE TABLE books (
            id INTEGER PRIMARY KEY,
            title TEXT,
            author_id INTEGER);
        SQL
    DB.execute(book_sql)
end

desc "set up database"
task :create_author_db do 

    author_sql = <<-SQL 
        CREATE TABLE authors (
            id INTEGER PRIMARY KEY,
            name TEXT);
        SQL
    DB.execute(author_sql)
end